inherit_from:
  - '~/configs/.rubocop.yml'

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'

  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
  SuggestExtensions: false

Layout/AccessModifierIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
